name: car_rent_app
description: Aplikasi penyewaan mobil menggunakan Flutter dan SQLite.
publish_to: 'none' # Mencegah publikasi ke pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependensi untuk Database SQLite
  sqflite: ^2.3.2        # Library utama untuk operasi database
  path: ^1.8.3           # Untuk mendapatkan path folder database

  # Dependensi untuk Manajemen State dan Data Sesi
  shared_preferences: ^2.2.2 # Untuk menyimpan status login (userId)

  # Dependensi untuk Formatting (Tanggal, Mata Uang)
  intl: ^0.18.1          # Untuk formatting tanggal dan harga

  # Ikon tambahan
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter disarankan
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Deklarasi folder aset
  assets:
    - assets/images/
